INSERT INTO TEAM(team_name)
  VALUES
    ('Sacramento Kings'),
    ('Phoenix Suns'),
    ('Los Angeles Lakers'),
    ('Dallas Mavericks'),
    ('Memphis Grizzlies'),
    ('New Orleans Pelicans'),
    ('Utah Jazz'),
    ('Portland Trail Blazers'),
    ('LA Clippers'),
    ('Denver Nuggets'),
    ('Minnesota Timberwolves'),
    ('Oklahoma City Thunder'),
    ('San Antonio Spurs'),
    ('Houston Rockets'),
    ('Golden State Warriors'),
    ('Chicago Bulls'),
    ('Atlanta Hawks'),
    ('Brooklyn Nets'),
    ('New York Knicks'),
    ('Indiana Pacers'),
    ('Orlando Magic'),
    ('Detroit Pistons'),
    ('Philadelphia 76ers'),
    ('Charlotte Hornets'),
    ('Miami Heat'),
    ('Milwaukee Bucks'),
    ('Washington Wizards'),
    ('Toronto Raptors'),
    ('Cleveland Cavaliers'),
    ('Boston Celtics')
