CREATE TABLE LIVE_TEAM_RECORD (
  id SERIAL PRIMARY KEY,
  OVER_UNDER DECIMAL NOT NULL,
  ACTUAL_WINS INT NOT NULL,
  LOSSES INT NOT NULL,
  DIFFERENTIAL DECIMAL NOT NULL,
  WIN_PERC DECIMAL NOT NULL,
  PYTHAG_TOTAL_WINS INT,
  PYTHAG_WINS_SO_FAR INT,
  IS_UNDER_IMPOSSIBLE BOOLEAN,
  IS_OVER_IMPOSSIBLE BOOLEAN,
  LAST_YEARS_RECORD VARCHAR(100)

);